[[data]]
window_size = [ 1920, 1080,]
mouse_coords = [ 1280, 605,]

[[data]]
window_size = [ 1756, 1013,]
mouse_coords = [ 1172, 574,]

[[data]]
window_size = [ 1920, 1032,]
mouse_coords = [ 1326, 584,]

[[data]]
window_size = [ 1788, 1032,]
mouse_coords = [ 1193, 583,]

[[data]]
window_size = [ 1864, 965,]
mouse_coords = [ 1308, 548,]

[[data]]
window_size = [ 1904, 965,]
mouse_coords = [ 1346, 547,]

[[data]]
window_size = [ 1551, 965,]
mouse_coords = [ 995, 548,]

[[data]]
window_size = [ 1797, 965,]
mouse_coords = [ 1242, 546,]

[[data]]
window_size = [ 1300, 870,]
mouse_coords = [ 799, 493,]

[[data]]
window_size = [ 1300, 763,]
mouse_coords = [ 864, 435,]

[[data]]
window_size = [ 1332, 790,]
mouse_coords = [ 882, 447,]

[[data]]
window_size = [ 1496, 877,]
mouse_coords = [ 991, 498,]

[[data]]
window_size = [ 1548, 928,]
mouse_coords = [ 1014, 527,]

[[data]]
window_size = [ 1626, 969,]
mouse_coords = [ 1067, 549,]

[[data]]
window_size = [ 1507, 1028,]
mouse_coords = [ 914, 582,]

[[data]]
window_size = [ 1623, 1028,]
mouse_coords = [ 1028, 582,]

